Self sovereign identity
Tribler/trustchain-superapp pull request #60
Opened 2021-02-28 22:55 UTC by InvictusRMC

# Introduction
This PR adds the 18 plus app and updates the Kotlin version used.

2021-03-31 12:41 UTC, synctext commented
Checks are failing. Can you update this PR? 
We're running towards a new release for EU-wide publicity before 8 April. @InvictusRMC @xoriole

2021-04-02 07:37 UTC, InvictusRMC commented
Please merge [kotlin-ipv8](https://github.com/Tribler/kotlin-ipv8/pull/43) first as this build will pass if that one is merged (and the submodule is updated).

2021-04-08 15:01 UTC, synctext commented
New student team at bsc level is starting after next week. So we need to get this polished and passing. @xoriole  :+1:

2021-04-19 08:14 UTC, synctext commented
@InvictusRMC @xoriole this PR will be repaired coming days.

2021-04-19 15:12 UTC, InvictusRMC commented
That was annoying to fix, some dependency hell: MusicDAO was using an old version of coroutines, clashing with the newer ones used. Their tests only work on Linux. so I had to set up a VM for this project. But everything seems to function as expected.

@xoriole it should be good to go.

2021-04-21 09:18 UTC, xoriole requested changes
Please remove the unnecessary example test files

2021-04-21 09:18 UTC, xoriole commented on ig-ssi/src/androidTest/java/nl/tudelft/trustchain/explorer/ExampleInstrumentedTest.kt
> +package nl.tudelft.trustchain.explorer
This example test file can be removed

2021-04-21 09:18 UTC, xoriole commented on ig-ssi/src/test/java/nl/tudelft/trustchain/explorer/ExampleUnitTest.kt
> +package nl.tudelft.trustchain.explorer
This test does not add any value, please remove it

2021-04-25 19:51 UTC, InvictusRMC commented
@xoriole thank you for the review. I've implemented your requested changes.

2021-04-26 08:46 UTC, xoriole approved these changes

2021-04-26 08:46 UTC, merged